{"name": "test_login_with_not_exist_login", "status": "passed", "description": "Тест на получение кода ошибки при попытке авторизации с несуществущим login", "start": 1723299414588, "stop": 1723299415116, "uuid": "dec2c2d7-3ec7-4d58-b9c0-77776ac9359f", "historyId": "fc892b85fcba37ce6f8773a5cd00ccda", "testCaseId": "fc892b85fcba37ce6f8773a5cd00ccda", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_with_not_exist_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-NLGTCNSI"}, {"name": "thread", "value": "20544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}